### ISSUE TITLE
A Restart opens a time window to get to the addon page and disable it.

### ISSUE THREAD

**Issue by mmmjffj** [mrigor/publicfox#39]
A restart of the computer and opening a fresh window allows for a small time frame where the user can get past publicfox and disable it. My son used it to disable the addons I have. Can you help with this?

**Comment by mrigor** [comment]
@mmmjffj please leave a review on  https://addons.mozilla.org/en-US/firefox/addon/public-fox/ to reach current developers/owners of the addon

this repo is around for archival purposes mostly
